#!/usr/bin/env python3
"""
Generate per-publication Hugo content pages from data/publications.yaml.

data/publications.yaml is a flat list of DOI entries with curation flags:
  - featured:    bool — eligible for the homepage section (top-k newest)
  - alt_text:    optional one-line note rendered under the venue on cards
  - description: optional curator/internal note, passed through to the
                 generated frontmatter but NOT rendered

For each DOI this script:

  1. Fetches the work record from the CrossRef REST API (cached on disk).
  2. Normalizes title / authors / venue / year.
  3. Writes content/publications/<slug>/index.md with `build.render = never`
     and `build.list = local`, so the page exists in `.Pages` for the
     /publications/ list template but produces no standalone HTML.

It also writes/refreshes content/publications/_index.md and prunes any
auto-generated page directories whose DOI is no longer in the YAML.

Usage (run from the site root):
    python scripts/build-publications.py              # incremental, uses cache
    python scripts/build-publications.py --refresh    # re-fetch every DOI
    python scripts/build-publications.py --refresh DOI [DOI ...]   # re-fetch some
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
import time
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install -r scripts/requirements.txt")

try:
    import requests
except ImportError:
    sys.exit("requests is required: pip install -r scripts/requirements.txt")


SITE_ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = SITE_ROOT / "data" / "publications.yaml"
CACHE_DIR = SITE_ROOT / "data" / ".crossref-cache"
PUB_DIR = SITE_ROOT / "content" / "publications"
LEGACY_FILE = SITE_ROOT / "content" / "publications.md"

CROSSREF_URL = "https://api.crossref.org/works/{doi}"
USER_AGENT = "hugo-azulprint/1.0 (mailto:contact@example.com)"
AUTOGEN_MARKER = "auto-generated by scripts/build-publications.py"


# ───────────────────────── helpers ─────────────────────────


def slugify(doi: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", doi.lower()).strip("-")


def initials(given: str) -> str:
    parts = re.split(r"[\s\-]+", given.strip())
    return "".join(f"{p[0].upper()}." for p in parts if p)


def format_author(a: dict[str, Any]) -> str:
    family = (a.get("family") or "").strip()
    given = (a.get("given") or "").strip()
    if family and given:
        return f"{family}, {initials(given)}"
    if family:
        return family
    return (a.get("name") or "").strip()


def pick_year(msg: dict[str, Any]) -> int | None:
    for key in ("published-print", "published-online", "issued", "created"):
        parts = (msg.get(key) or {}).get("date-parts") or []
        if parts and parts[0]:
            return int(parts[0][0])
    return None


def pick_venue(msg: dict[str, Any], doi: str) -> str:
    prefix = doi.split("/", 1)[0]
    if prefix == "10.1101":
        return "bioRxiv"
    if prefix == "10.48550" or doi.lower().startswith("arxiv:"):
        return "arXiv"

    is_preprint = msg.get("type") == "posted-content" and msg.get("subtype") == "preprint"
    if is_preprint:
        inst = msg.get("institution") or []
        if inst and isinstance(inst, list):
            name = (inst[0] or {}).get("name")
            if name:
                return name
        ct = msg.get("container-title") or []
        if ct:
            return ct[0]
        return msg.get("publisher") or "preprint"

    ct = msg.get("container-title") or []
    if ct:
        return ct[0]
    return msg.get("publisher") or ""


def normalize_title(t: str) -> str:
    return re.sub(r"\s+", " ", t).strip()


# ───────────────────────── CrossRef ─────────────────────────


def fetch_crossref(doi: str, force: bool) -> dict[str, Any]:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    cache_path = CACHE_DIR / f"{slugify(doi)}.json"
    if cache_path.exists() and not force:
        with cache_path.open() as f:
            return json.load(f)

    url = CROSSREF_URL.format(doi=requests.utils.quote(doi, safe="/"))
    resp = requests.get(url, headers={"User-Agent": USER_AGENT}, timeout=20)
    if resp.status_code == 404:
        sys.exit(f"CrossRef has no record for DOI {doi!r}. Check the DOI.")
    resp.raise_for_status()
    payload = resp.json()
    cache_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False))
    # Stay well under CrossRef's polite-pool guidance (50 rps).
    time.sleep(0.1)
    return payload


# ───────────────────────── page emit ─────────────────────────


def build_entry(doi: str, featured: bool, description: str | None,
                alt_text: str | None,
                refresh_all: bool, refresh_some: set[str]) -> dict[str, Any]:
    force = refresh_all or (doi in refresh_some)
    payload = fetch_crossref(doi, force=force)
    msg = payload.get("message") or {}

    titles = msg.get("title") or []
    title = normalize_title(titles[0]) if titles else doi
    authors = [format_author(a) for a in (msg.get("author") or [])]
    authors = [a for a in authors if a]
    year = pick_year(msg)
    venue = pick_venue(msg, doi)

    fm = {
        "title": title,
        "doi": doi,
        "doi_url": f"https://doi.org/{doi}",
        "authors": authors,
        "venue": venue,
        "year": year,
        "featured": bool(featured),
        "build": {"render": "never", "list": "local"},
    }
    if year:
        fm["date"] = f"{year}-01-01"
    if alt_text:
        fm["alt_text"] = alt_text
    if description:
        fm["description"] = description
    return fm


def write_page(slug: str, fm: dict[str, Any]) -> Path:
    dest_dir = PUB_DIR / slug
    dest_dir.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(fm, sort_keys=False, allow_unicode=True, width=1000)
    out = dest_dir / "index.md"
    out.write_text(f"---\n# {AUTOGEN_MARKER}\n# Edit data/publications.yaml and re-run.\n{body}---\n")
    return out


def write_section_index() -> None:
    PUB_DIR.mkdir(parents=True, exist_ok=True)
    idx = PUB_DIR / "_index.md"
    if idx.exists():
        existing = idx.read_text()
        if AUTOGEN_MARKER not in existing:
            return
    idx.write_text(
        "---\n"
        f"# {AUTOGEN_MARKER}\n"
        "title: Publications\n"
        "---\n"
    )


def prune_stale(keep_slugs: set[str]) -> list[str]:
    removed: list[str] = []
    if not PUB_DIR.exists():
        return removed
    for child in PUB_DIR.iterdir():
        if not child.is_dir() or child.name in keep_slugs:
            continue
        idx = child / "index.md"
        if idx.exists() and AUTOGEN_MARKER in idx.read_text():
            shutil.rmtree(child)
            removed.append(child.name)
    return removed


# ───────────────────────── main ─────────────────────────


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--refresh",
        nargs="*",
        metavar="DOI",
        help="Bypass the cache. With no DOIs, re-fetches all; with DOIs, re-fetches only those.",
    )
    args = ap.parse_args()

    refresh_all = args.refresh is not None and len(args.refresh) == 0
    refresh_some = set(args.refresh or [])

    if not DATA_FILE.exists():
        sys.exit(f"missing {DATA_FILE}")

    with DATA_FILE.open() as f:
        entries = yaml.safe_load(f) or []
    if not isinstance(entries, list):
        sys.exit(f"{DATA_FILE} must be a list of DOI entries (see file header).")

    if LEGACY_FILE.exists():
        LEGACY_FILE.unlink()
        print(f"removed legacy {LEGACY_FILE.relative_to(SITE_ROOT)}")

    write_section_index()

    keep_slugs: set[str] = set()
    for entry in entries:
        doi = entry.get("doi")
        if not doi:
            sys.exit(f"entry without doi in {DATA_FILE}: {entry!r}")
        slug = slugify(doi)
        keep_slugs.add(slug)

        fm = build_entry(
            doi=doi,
            featured=bool(entry.get("featured", False)),
            description=entry.get("description"),
            alt_text=entry.get("alt_text"),
            refresh_all=refresh_all,
            refresh_some=refresh_some,
        )
        out = write_page(slug, fm)
        print(f"wrote {out.relative_to(SITE_ROOT)}")

    removed = prune_stale(keep_slugs)
    for name in removed:
        print(f"pruned content/publications/{name}/")

    return 0


if __name__ == "__main__":
    sys.exit(main())
