#!/usr/bin/env python3
"""
Auto-generate content/tags/<slug>/_index.md files for every tag used in
the site, so each tag has a term page even when no taxonomy aggregation
would otherwise create one (e.g. tag used only on `list: local` pubs/awards).

Sources scanned:
  - frontmatter `tags:` on any content file outside content/tags/
  - research.md `interests[].tag`

Files carrying the autogen marker are rewritten on re-run; user-customised
files (marker removed) are preserved. Stale tag pages (slug not in use) are
listed and the user is prompted before any deletion.

Usage (run from the site root):
    python scripts/build-tags.py              # interactive prompt before prune
    python scripts/build-tags.py --prune-yes  # skip prompt, prune anyway
"""
from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install -r scripts/requirements.txt")


SITE_ROOT = Path(__file__).resolve().parent.parent
CONTENT_DIR = SITE_ROOT / "content"
TAGS_DIR = CONTENT_DIR / "tags"
AUTOGEN_MARKER = "auto-generated by scripts/build-tags.py"


def parse_frontmatter(text: str) -> dict:
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end < 0:
        return {}
    try:
        return yaml.safe_load(text[3:end]) or {}
    except yaml.YAMLError:
        return {}


def collect_tags() -> set[str]:
    tags: set[str] = set()
    for md in CONTENT_DIR.rglob("*.md"):
        try:
            if md.is_relative_to(TAGS_DIR):
                continue
        except AttributeError:  # py<3.9 fallback
            if TAGS_DIR in md.parents:
                continue
        fm = parse_frontmatter(md.read_text(encoding="utf-8", errors="ignore"))
        for t in fm.get("tags") or []:
            tags.add(str(t))
        for entry in fm.get("interests") or []:
            if isinstance(entry, dict) and entry.get("tag"):
                tags.add(str(entry["tag"]))
    return tags


def slugify(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def derive_title(slug: str) -> str:
    return slug.replace("-", " ").replace("_", " ").capitalize()


def write_term_index(slug: str) -> Path | None:
    out = TAGS_DIR / slug / "_index.md"
    if out.exists() and AUTOGEN_MARKER not in out.read_text(encoding="utf-8"):
        return None  # user-customised, leave alone
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        f"---\n"
        f"# {AUTOGEN_MARKER}\n"
        f"# Edit `title:` or add body content. To stop auto-management,\n"
        f"# remove the autogen marker line above.\n"
        f'title: "{derive_title(slug)}"\n'
        f"---\n",
        encoding="utf-8",
    )
    return out


def find_stale(keep_slugs: set[str]) -> list[tuple[str, bool]]:
    """Return [(slug, is_autogen)] for tag dirs whose slug is not in use."""
    stale: list[tuple[str, bool]] = []
    if not TAGS_DIR.exists():
        return stale
    for child in sorted(TAGS_DIR.iterdir()):
        if not child.is_dir() or child.name in keep_slugs:
            continue
        idx = child / "_index.md"
        if not idx.exists():
            continue
        is_autogen = AUTOGEN_MARKER in idx.read_text(encoding="utf-8")
        stale.append((child.name, is_autogen))
    return stale


def confirm_prune(stale: list[tuple[str, bool]], force: bool) -> bool:
    print(f"\n{len(stale)} stale tag page(s) found:")
    for slug, is_autogen in stale:
        tag = "[autogen]" if is_autogen else "[customised]"
        print(f"  {tag:<13} content/tags/{slug}/")
    if force:
        return True
    if not sys.stdin.isatty():
        print("(non-interactive: not pruning. Re-run with --prune-yes to prune.)")
        return False
    resp = input(f"Prune these {len(stale)} tag pages? [y/N] ").strip().lower()
    return resp in {"y", "yes"}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument(
        "--prune-yes",
        action="store_true",
        help="skip the confirmation prompt and prune stale pages",
    )
    args = parser.parse_args()

    raw = collect_tags()
    slugs = {slugify(t) for t in raw}
    TAGS_DIR.mkdir(parents=True, exist_ok=True)
    for slug in sorted(slugs):
        out = write_term_index(slug)
        if out:
            print(f"wrote {out.relative_to(SITE_ROOT)}")

    stale = find_stale(slugs)
    if stale and confirm_prune(stale, args.prune_yes):
        for slug, _ in stale:
            shutil.rmtree(TAGS_DIR / slug)
            print(f"pruned content/tags/{slug}/")
    elif stale:
        print("kept (no prune).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
