#!/usr/bin/env python3
"""
Generate per-award Hugo content pages from data/awards.yaml.

data/awards.yaml is a flat list of award entries with curation flags:
  - title:    award name (required)
  - year:     award year (required)
  - org:      awarding organization (optional)
  - category: "award" | "funding" — drives chip styling (optional)
  - featured: true → eligible for the homepage section
  - alt_text: optional one-line note rendered on cards

For each entry this script writes content/awards/<slug>/index.md with
`build.render = never` and `build.list = local`, so the page exists in
`.Pages` for the /awards/ list template but produces no standalone HTML.

It also writes/refreshes content/awards/_index.md and prunes any
auto-generated page directories whose entry is no longer in the YAML.

Usage (run from the site root):
    python scripts/build-awards.py
"""
from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install -r scripts/requirements.txt")


SITE_ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = SITE_ROOT / "data" / "awards.yaml"
AWARDS_DIR = SITE_ROOT / "content" / "awards"
LEGACY_FILE = SITE_ROOT / "content" / "awards.md"

AUTOGEN_MARKER = "auto-generated by scripts/build-awards.py"


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def entry_slug(entry: dict[str, Any]) -> str:
    year = str(entry.get("year") or "").strip()
    title = str(entry.get("title") or "").strip()
    base = f"{year}-{title}" if year else title
    slug = slugify(base)
    if not slug:
        sys.exit(f"entry has no usable title/year for slug: {entry!r}")
    return slug


def build_entry(entry: dict[str, Any]) -> dict[str, Any]:
    title = (entry.get("title") or "").strip()
    if not title:
        sys.exit(f"entry without title in {DATA_FILE}: {entry!r}")
    year = entry.get("year")
    if year is None:
        sys.exit(f"entry without year in {DATA_FILE}: {entry!r}")

    fm: dict[str, Any] = {
        "title": title,
        "year": year,
        "featured": bool(entry.get("featured", False)),
        "build": {"render": "never", "list": "local"},
    }
    # Use the numeric year for chronological ordering; the year field stays
    # as written (string or int) for display.
    try:
        year_num = int(str(year)[:4])
        fm["date"] = f"{year_num}-01-01"
    except ValueError:
        pass
    if entry.get("org"):
        fm["org"] = entry["org"]
    if entry.get("category"):
        fm["category"] = entry["category"]
    if entry.get("alt_text"):
        fm["alt_text"] = entry["alt_text"]
    return fm


def write_page(slug: str, fm: dict[str, Any]) -> Path:
    dest_dir = AWARDS_DIR / slug
    dest_dir.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(fm, sort_keys=False, allow_unicode=True, width=1000)
    out = dest_dir / "index.md"
    out.write_text(f"---\n# {AUTOGEN_MARKER}\n# Edit data/awards.yaml and re-run.\n{body}---\n")
    return out


def write_section_index() -> None:
    AWARDS_DIR.mkdir(parents=True, exist_ok=True)
    idx = AWARDS_DIR / "_index.md"
    if idx.exists():
        existing = idx.read_text()
        if AUTOGEN_MARKER not in existing:
            return
    idx.write_text(
        "---\n"
        f"# {AUTOGEN_MARKER}\n"
        "title: Awards\n"
        "label: Awards & funding\n"
        "---\n"
    )


def prune_stale(keep_slugs: set[str]) -> list[str]:
    removed: list[str] = []
    if not AWARDS_DIR.exists():
        return removed
    for child in AWARDS_DIR.iterdir():
        if not child.is_dir() or child.name in keep_slugs:
            continue
        idx = child / "index.md"
        if idx.exists() and AUTOGEN_MARKER in idx.read_text():
            shutil.rmtree(child)
            removed.append(child.name)
    return removed


def main() -> int:
    if not DATA_FILE.exists():
        sys.exit(f"missing {DATA_FILE}")

    with DATA_FILE.open() as f:
        entries = yaml.safe_load(f) or []
    if not isinstance(entries, list):
        sys.exit(f"{DATA_FILE} must be a list of entries (see file header).")

    if LEGACY_FILE.exists():
        LEGACY_FILE.unlink()
        print(f"removed legacy {LEGACY_FILE.relative_to(SITE_ROOT)}")

    write_section_index()

    keep_slugs: set[str] = set()
    for entry in entries:
        slug = entry_slug(entry)
        keep_slugs.add(slug)
        fm = build_entry(entry)
        out = write_page(slug, fm)
        print(f"wrote {out.relative_to(SITE_ROOT)}")

    removed = prune_stale(keep_slugs)
    for name in removed:
        print(f"pruned content/awards/{name}/")

    return 0


if __name__ == "__main__":
    sys.exit(main())
